### ISSUE TITLE
Meteor constantly failing when trying to do reverse geocode.

### ISSUE THREAD

**Issue by dmitry-sher** [aldeed/meteor-geocoder#12]
Here's the problem:
In the package, in geocoder.js:34 you are calling 

    g.reverse(lat, lng, callback);

And the geocoder waits for object and callback, in .npm/package/node_modules/node-geocoder/lib/geocoder.js:52

    Geocoder.prototype.reverse = function(query, callback) {

where query is

    {lat:<number>,lon:<number>}  lat: Latitude, lon: Longitude

So the correct way to call reverse geocoding is

    g.reverse({lat: lat, lon: lng}, callback);

**Comment by otech-nl** [comment]
Me too. I asked on http://stackoverflow.com/q/32967078/5251833

**Comment by aldeed** [comment]
Fixed in 0.3.8

**Comment by otech-nl** [comment]
Works!

Thanks for this quick fix :)

**Comment by dmitry-sher** [comment]
thanks a lot!
